[theme]
primaryColor = "#CBA6F7"
backgroundColor = "#181825"
secondaryBackgroundColor = "#242438"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
