[theme]
primaryColor = "#D0BCFF"
backgroundColor = "#121318"
secondaryBackgroundColor = "#1E1F25"
textColor = "#E2E2E9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
